### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by b-rockx** [GetRektByMe/PyAnimeList#7]
Receiving  the following error 
`aiohttp.client_exceptions.ClientConnectorError: [Errno 1] Cannot connect to host myanimelist.net:443 ssl:True [Can not connect to myanimelist.net:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)]]`

by adding 

`connector=aiohttp.TCPConnector(verify_ssl=False)`
to line 53 in client
`with aiohttp.ClientSession(auth=self._auth, headers={"User-Agent": self.user_agent}, connector=aiohttp.TCPConnector(verify_ssl=False)) as session:`
 and to line 72 in client
`with aiohttp.ClientSession(auth=self._auth, headers={"User-Agent": self.user_agent},connector=aiohttp.TCPConnector(verify_ssl=False)) as session:`

I was able to resolve the issue.

**Comment by byronvanstien** [comment]
Honestly not going to ever recommend not verifying SSL certificates.
Probably an error on MAL's end since when I tested it everything was fine.
@b-rockx does this error still occur when enforcing the validity of the SSL cert?

**Comment by byronvanstien** [comment]
No response. Closing issue.
