### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by MrTyton** [GetRektByMe/PyAnimeList#8]
It seems like MAL has implemented a new security measure that forces you to relog manually on the site if you haven't logged in there in a while, requiring you to do a captcha. Is there is a way for us to make MAL think that we've logged on or that we have fulfilled the captcha requirement?

**Comment by byronvanstien** [comment]
Not happening for a few reasons.

1. Awkward
2. Breach of MAL ToS
3. I've spoken to Xinil and a MAL dev and the reason for this is that people are using it to brute force MAL accounts, which is the reason for the captcha.

As a proposed solution, upon the requirement of the captcha being told to us I could raise a custom exception for you to handle, so you can tell the user to go do that.

I don't *really* see much of a point thought considering MAL is in the works of a new API.

**Comment by MrTyton** [comment]
Custom exception would be nice. Right now it just raises a 403 which I was really confused as to why it did so until I figured it out.

Those are all completely reasonable reasons though.
